### ISSUE TITLE
Differences with jwt gem

### ISSUE THREAD

**Issue by javiercr** [chupipandi/jwt-rb#1]
First of all thank you for putting all of this together.

I was wondering what's the difference (from a consumer perspective) from this gem and the [jwt gem](https://rubygems.org/gems/jwt) hosted on [progrium/ruby-jwt](https://github.com/progrium/ruby-jwt).

It's the first time I am using JSON Web Tokens and it is a bit confusing seeing two gems that seem to do exactly the same.

Thanks!

**Comment by Foxandxss** [comment]
As today probably not that much. In the past they did not support any type of claims so all the expiration had to be done by hand, seems like they support expiration now, but not really sure about the other claims.

**Comment by javiercr** [comment]
Wow, thank you for the ultra fast answer! :) I'll give a try to both.
